# -*- coding: utf-8 -*-

"""__notebook_source__.ipynb



Automatically generated by Colab.



Original file is located at

    https://colab.research.google.com/drive/1xCdKihOoLbrCAVnxZGnJfr9f3M1u46-F

"""



!pip install tensorflow matplotlib numpy opencv-python



import tensorflow as tf

from tensorflow.keras import layers, models

import matplotlib.pyplot as plt

import numpy as np

from tensorflow.keras.datasets import mnist

import cv2



print("✅ Libraries imported successfully")

print(f"TensorFlow version: {tf.__version__}")



from tensorflow.keras.datasets import mnist

import tensorflow_datasets as tfds



# Install tensorflow_datasets if needed

!pip install tensorflow-datasets



# Load EMNIST Letters (A-Z uppercase and lowercase)

dataset, info = tfds.load('emnist/letters', with_info=True, as_supervised=True)

train_dataset = dataset['train']

test_dataset = dataset['test']



print("✅ EMNIST Letters dataset loaded")

print(f"Dataset info: {info}")



IMG_SIZE = 28  # EMNIST images are 28x28

BATCH_SIZE = 32



def preprocess(image, label):

    # EMNIST images need to be transposed and rotated for correct orientation

    image = tf.transpose(image, perm=[1, 0, 2])  # Transpose

    image = tf.image.rot90(image, k=0)  # Rotate 270 degrees (or -90)



    # Normalize pixel values to [0, 1]

    image = tf.cast(image, tf.float32) / 255.0

    # EMNIST labels are 1-26 for A-Z, we need 0-25

    label = label - 1

    return image, label



# Apply preprocessing

train_ds = train_dataset.map(preprocess).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

test_ds = test_dataset.map(preprocess).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)



# Split test into validation and test

val_size = int(0.5 * info.splits['test'].num_examples)

val_ds = test_ds.take(val_size // BATCH_SIZE)

test_ds = test_ds.skip(val_size // BATCH_SIZE)



# Class names (A-Z)

class_names = [chr(i) for i in range(65, 91)]  # A-Z uppercase letters

num_classes = len(class_names)



print(f"✅ Number of classes: {num_classes}")

print(f"Class names: {class_names[:10]}...")



plt.figure(figsize=(15, 8))

images_shown = 0

for images, labels in train_ds.take(1):

    for i in range(min(20, len(images))):

        plt.subplot(4, 5, i + 1)

        plt.imshow(images[i].numpy().squeeze(), cmap='gray')

        plt.title(f"Label: {class_names[labels[i].numpy()]}")

        plt.axis('off')

        images_shown += 1

plt.suptitle("Sample Images from EMNIST Letters Training Set", fontsize=16)

plt.tight_layout()

plt.show()

print(f"✅ Displayed {images_shown} sample images")



model = models.Sequential([

    layers.Conv2D(32, 3, activation='relu', input_shape=(28, 28, 1)),

    layers.MaxPooling2D(),

    layers.Conv2D(64, 3, activation='relu'),

    layers.MaxPooling2D(),

    layers.Conv2D(128, 3, activation='relu'),

    layers.Flatten(),

    layers.Dense(256, activation='relu'),

    layers.Dropout(0.5),

    layers.Dense(num_classes, activation='softmax')

])



model.summary()

print("✅ Model architecture created")



model.compile(

    optimizer='adam',

    loss='sparse_categorical_crossentropy',

    metrics=['accuracy']

)

print("✅ Model compiled")



print("🚀 Starting training...")

history = model.fit(

    train_ds,

    validation_data=val_ds,

    epochs=5,

    verbose=1

)

print("✅ Training completed!")



plt.figure(figsize=(14, 5))



plt.subplot(1, 2, 1)

plt.plot(history.history['accuracy'], label='Training Accuracy', marker='o')

plt.plot(history.history['val_accuracy'], label='Validation Accuracy', marker='s')

plt.title('Model Accuracy over Epochs', fontsize=14, fontweight='bold')

plt.xlabel('Epoch')

plt.ylabel('Accuracy')

plt.legend()

plt.grid(True, alpha=0.3)



plt.subplot(1, 2, 2)

plt.plot(history.history['loss'], label='Training Loss', marker='o')

plt.plot(history.history['val_loss'], label='Validation Loss', marker='s')

plt.title('Model Loss over Epochs', fontsize=14, fontweight='bold')

plt.xlabel('Epoch')

plt.ylabel('Loss')

plt.legend()

plt.grid(True, alpha=0.3)



plt.tight_layout()

plt.show()

print("✅ Training history plotted")



print("📊 Evaluating on test set...")

test_loss, test_accuracy = model.evaluate(test_ds, verbose=1)

print(f"\n✅ Test Accuracy: {test_accuracy*100:.2f}%")

print(f"✅ Test Loss: {test_loss:.4f}")



print("🔮 Getting predictions on validation set...")

y_true_val = []

y_pred_val = []



for images, labels in val_ds:

    preds = model.predict(images, verbose=0)

    y_true_val.extend(labels.numpy())

    y_pred_val.extend(np.argmax(preds, axis=1))



y_true_val = np.array(y_true_val)

y_pred_val = np.array(y_pred_val)



# Calculate accuracy

val_accuracy = np.mean(y_true_val == y_pred_val)



plt.figure(figsize=(12, 5))

plt.scatter(range(len(y_true_val)), y_true_val, label="True Labels", alpha=0.5, s=10, c='blue')

plt.scatter(range(len(y_pred_val)), y_pred_val, label="Predicted Labels", alpha=0.5, s=10, c='red')

plt.title("Validation Set: True vs Predicted Labels", fontsize=14, fontweight='bold')

plt.xlabel("Sample Index")

plt.ylabel("Class Index (0=A, 25=Z)")

plt.legend()

plt.grid(True, alpha=0.3)

plt.tight_layout()

plt.show()

print("✅ True vs Predicted scatter plot created")



print("📊 Visualizing TRAINING set predictions...")

images_train, labels_train = None, None

for imgs, lbls in train_ds.take(1):

    images_train = imgs

    labels_train = lbls

    break



preds_train = model.predict(images_train, verbose=0)

pred_classes_train = np.argmax(preds_train, axis=1)



N = 20

plt.figure(figsize=(16, 8))

for i in range(N):

    plt.subplot(4, 5, i + 1)

    plt.imshow(images_train[i].numpy().squeeze(), cmap="gray")

    plt.axis("onn")



    true_label = labels_train[i].numpy()

    pred_label = pred_classes_train[i]



    true_char = class_names[true_label]

    pred_char = class_names[pred_label]



    color = "green" if true_label == pred_label else "red"

    plt.title(f"T: {true_char} | P: {pred_char}", color=color, fontsize=11, fontweight='bold')



plt.suptitle("TRAINING Set: True vs Predicted Letters", fontsize=16, fontweight='bold')

plt.tight_layout()

plt.show()

print("✅ Training set prediction visualization complete")



print("📊 Visualizing VALIDATION set predictions...")

images_val, labels_val = None, None

for imgs, lbls in val_ds.take(1):

    images_val = imgs

    labels_val = lbls

    break



preds_val = model.predict(images_val, verbose=0)

pred_classes_val = np.argmax(preds_val, axis=1)



N = 20

plt.figure(figsize=(16, 8))

for i in range(N):

    plt.subplot(4, 5, i + 1)

    plt.imshow(images_val[i].numpy().squeeze(), cmap="gray")

    plt.axis("off")



    true_label = labels_val[i].numpy()

    pred_label = pred_classes_val[i]



    true_char = class_names[true_label]

    pred_char = class_names[pred_label]



    color = "green" if true_label == pred_label else "red"

    plt.title(f"T: {true_char} | P: {pred_char}", color=color, fontsize=11, fontweight='bold')



plt.suptitle("VALIDATION Set: True vs Predicted Letters", fontsize=16, fontweight='bold')

plt.tight_layout()

plt.show()

print("✅ Validation set prediction visualization complete")



print("📊 Visualizing TEST set predictions...")

images_test, labels_test = None, None

for imgs, lbls in test_ds.take(1):

    images_test = imgs

    labels_test = lbls

    break



preds_test = model.predict(images_test, verbose=0)

pred_classes_test = np.argmax(preds_test, axis=1)



N = 20

plt.figure(figsize=(16, 8))

for i in range(N):

    plt.subplot(4, 5, i + 1)

    plt.imshow(images_test[i].numpy().squeeze(), cmap="gray")

    plt.axis("off")



    true_label = labels_test[i].numpy()

    pred_label = pred_classes_test[i]



    true_char = class_names[true_label]

    pred_char = class_names[pred_label]



    color = "green" if true_label == pred_label else "red"

    plt.title(f"T: {true_char} | P: {pred_char}", color=color, fontsize=11, fontweight='bold')



plt.suptitle("TEST Set: True vs Predicted Letters", fontsize=16, fontweight='bold')

plt.tight_layout()

plt.show()

print("✅ Test set prediction visualization complete")



model.save('emnist_letter_model.h5')